### ISSUE TITLE
Applying resources to kubevirt namespace fails with "caches not synchronized" 

### ISSUE THREAD

**Issue by booxter** [openshift-metalkube/dev-scripts#141] opened 2019-03-08 21:39 UTC
When applying the `kubevirt` manifests from `manifests/` directory, `oc` fails
to post the resources with the following errors:

```
[root@zeus07 manifests]# oc --config ../ocp/auth/kubeconfig apply -f 110_cnv_kubevirt_op.yaml 
Warning: oc apply should be used on resource created by either oc create --save-config or oc apply
Warning: oc apply should be used on resource created by either oc create --save-config or oc apply
customresourcedefinition.apiextensions.k8s.io/kubevirts.kubevirt.io configured
Warning: oc apply should be used on resource created by either oc create --save-config or oc apply
clusterrole.rbac.authorization.k8s.io/kubevirt.io:operator configured
Warning: oc apply should be used on resource created by either oc create --save-config or oc apply
clusterrolebinding.rbac.authorization.k8s.io/kubevirt-operator configured
Error from server (Forbidden): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{},\"labels\":{\"kubevirt.io\":\"\"},\"name\":\"kubevirt\",\"namespace\":\"\"}}\n"},"namespace":""}}
to:
Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace"
Name: "kubevirt", Namespace: ""
Object: &{map["kind":"Namespace" "apiVersion":"v1" "metadata":map["name":"kubevirt" "selfLink":"/api/v1/namespaces/kubevirt" "uid":"cfc4fdce-41bb-11e9-a9c0-52fdfc072182" "resourceVersion":"904" "creationTimestamp":"2019-03-08T16:04:11Z" "labels":map["kubevirt.io":""]] "spec":map["finalizers":["kubernetes"]] "status":map["phase":"Active"]]}
for: "110_cnv_kubevirt_op.yaml": namespaces "kubevirt" is forbidden: caches not synchronized
Error from server (Forbidden): error when creating "110_cnv_kubevirt_op.yaml": serviceaccounts "kubevirt-operator" is forbidden: caches not synchronized
Error from server (Forbidden): error when creating "110_cnv_kubevirt_op.yaml": deployments.apps "virt-operator" is forbidden: caches not synchronized
```

When we switch to `kube-system` namespace then it works fine.

The same error happens when manifests are applied by `openshift-install`
itself, as in https://github.com/metalkube/dev-scripts/pull/127.

I plan to post a PR that switches to `kube-system` to make progress on
deployment. This issue will be used to track investigation on reasons behind
the failure and to revert back to `kubevirt` namespace once we have the root
cause.

**Comment by hardys** [comment] 2019-03-19 11:55
Some discussion with @vrutkovs on slack indicates this may be due to cert rotation being broken, workaround is `oc get csr -o name | xargs -n 1 oc adm certificate approve`

**Comment by dhellmann** [comment] 2019-03-19 14:07
Do we feel like that's a short-term state, or should we add a script to make it easier to remember that cantrip?

**Comment by russellb** [comment] 2019-03-21 21:32
This issue looks related: https://github.com/openshift/cluster-machine-approver/issues/15

**Comment by russellb** [comment] 2019-03-21 21:49
My machine-approver log has a bunch of:

```
I0321 18:09:39.113975       1 main.go:97] CSR csr-grgft added
I0321 18:09:39.133134       1 main.go:123] CSR csr-grgft not authorized: No target machine
I0321 18:14:32.453059       1 main.go:97] CSR csr-f66gv added
I0321 18:14:32.464451       1 main.go:123] CSR csr-f66gv not authorized: No target machine
I0321 18:18:11.088381       1 main.go:97] CSR csr-jmf46 added
I0321 18:18:11.102598       1 main.go:123] CSR csr-jmf46 not authorized: No target machine
I0321 18:22:27.112564       1 main.go:97] CSR csr-zxjkn added
I0321 18:22:27.127977       1 main.go:123] CSR csr-zxjkn not authorized: No target machine
I0321 18:27:20.454085       1 main.go:97] CSR csr-f85k9 added
```

The code of interest is authorizeCSR() in here:

https://github.com/openshift/cluster-machine-approver/blob/master/csr_check.go#L91

It's failing right now as it can't find a `Machine` with a `NodeRef` with a name that matches the requestor.  The request includes something like `machine-0`, and that does match the name in Nodes in our env.

The issue appears to be that `NodeRef` isn't getting set on our Machine.

and *that* is because we don't have our actuator / machine controller running.  That's what would be setting `NodeRef`.

If I'm reading all this right, we need to complete integration of our cluster-api provider to get this to work properly.

https://github.com/openshift/machine-api-operator/pull/235

**Comment by russellb** [comment] 2019-03-21 21:52
... I'll add that this is one of those weird cases of "this could have never worked", so maybe something changed recently since we didn't see this earlier?

**Comment by abhinavdahiya** [comment] 2019-03-21 22:20
```
Error from server (Forbidden): error when creating "110_cnv_kubevirt_op.yaml": serviceaccounts "kubevirt-operator" is forbidden: caches not synchronized
Error from server (Forbidden): error when creating "110_cnv_kubevirt_op.yaml": deployments.apps "virt-operator" is forbidden: caches not synchronized
```
you are seeing these errors because openshift-apiserver is not running. Openshift-apiserver provides some of the api required to run admission controllers in the kube-apiserver, therefore kube-apiserver rejects objects in all namespaces until openshift-apiserver is running.

Now because there are components that need to be running in the cluster before openshift-apiserver, those Cluster Operators make use of run-level 0/1 to skip the admission controllers that depend on openshit-apiserver.
eg: https://github.com/openshift/machine-api-operator/blob/master/install/0000_30_machine-api-operator_00_namespace.yaml#L7

There might be conditions that prevent only some namespaces to have run-levels and master team can guide you on that a bit more.

**Comment by russellb** [comment] 2019-03-22 15:35
using a CI produced release image from https://github.com/openshift/machine-api-operator/pull/235, we brought up a cluster that ran our cluster-api-provider-baremetal images.  The machine controller is crash looping though, which is now discussed in: https://github.com/metalkube/cluster-api-provider-baremetal/pull/39

**Comment by russellb** [comment] 2019-03-22 19:59
This is where NodeRef gets set: 
https://github.com/metalkube/cluster-api-provider-baremetal/blob/master/vendor/sigs.k8s.io/cluster-api/pkg/controller/node/node.go#L76

**Comment by russellb** [comment] 2019-04-01 19:11
Since it's not clear if the originally reported issues is caused by the cert approval issue, i'm going to open a new issue to track that.

**Comment by russellb** [comment] 2019-04-01 19:15
cert approval issue is now tracked in #260

**Comment by hardys** [comment] 2019-04-10 15:23
I think with the csr approval workarounds landed this can be closed, and we'll track remaining issues around that via #260?

**Comment by russellb** [comment] 2019-04-23 01:16
I'm closing this as stale, please file a new issue if you have more problems.

**Closed by russellb** 2019-04-23 01:16 UTC
