### ISSUE TITLE
There are no 'baremetal' hosts

### ISSUE THREAD

**Issue by e-minguez** [openshift-metalkube/dev-scripts#252] opened 2019-04-01 14:30 UTC
```
$ oc explain baremetalhosts.metalkube.org
KIND:     BareMetalHost
VERSION:  metalkube.org/v1alpha1

DESCRIPTION:
     <empty>

$ oc get baremetalhosts --all-namespaces
No resources found.
$ oc version
Client Version: version.Info{Major:"4", Minor:"0+", GitVersion:"v4.0.22", GitCommit:"219bbe2f0c", GitTreeState:"", BuildDate:"2019-03-10T22:23:11Z", GoVersion:"", Compiler:"", Platform:""}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4+eae8710", GitCommit:"eae8710", GitTreeState:"clean", BuildDate:"2019-03-30T18:01:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
$ git rev-parse HEAD
31b1359f92750d290fcc972350bc3a1c2dd6ebda
$ oc get nodes
NAME       STATUS   ROLES           AGE     VERSION
master-0   Ready    master,worker   3h18m   v1.12.4+50c2f2340a
master-1   Ready    master,worker   3h18m   v1.12.4+50c2f2340a
master-2   Ready    master,worker   3h18m   v1.12.4+50c2f2340a
```

Is the baremetal crd only for workers or nodes deployed with the baremetal operator?

**Comment by hardys** [comment] 2019-04-01 14:34
Yes it's only for the workers deployed via the baremetal operator, and we don't deploy any workers yet via dev-scripts (having script that does that manually would be useful though)

cc @dhellmann

**Comment by dhellmann** [comment] 2019-04-01 15:44
See https://github.com/metalkube/baremetal-operator/pull/106

**Comment by hardys** [comment] 2019-04-08 10:29
Closing as I think this is expected and not a bug

**Closed by hardys** 2019-04-08 10:29 UTC
